name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python3
        uses: actions/setup-python@v2
        with:
          python-versions: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Run pytest-coverage
        run: |
          make test-coverage